# This is a basic workflow to help you get started with Actions

name: Declassified UK RSS filter

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
    
      - name: Install Python packages
        run: python3 -m pip install lxml requests beautifulsoup4
      
      - name: Run filter script
        working-directory: ./declassified-uk-rss
        run: python3 declassified-uk-rss.py

      - name: Upload filtered RSS
        uses: actions/upload-artifact@v2.2.1
        with:
          # Artifact name
          name: filtered-rss
          # A file, directory or wildcard pattern that describes what to upload
          path: ./declassified-uk-rss/filtered.xml
